baseURL = "https://frankjordan.de/"
languageCode = "en-us"
title = "Frank Jordan"
theme = "m10c"
paginate = 5

[params]
  author = "Frank Jordan"
  description = "Network & Automation"
  avatar = "avatar.jpg"
  [[params.social]]
    icon = "github"
    name = "github"
    url = "https://github.com/chasf"
  [[params.social]]
    icon = "linkedin"
    name = "linkedin"
    url = "https://www.linkedin.com/in/frankjordangbg"
  [[params.social]]
    icon = "x"
    name = "xing"
    url = "https://www.xing.com/profile/Frank_Jordan16"

  # Theme
  [params.style]
    darkestColor = "#242930"
    darkColor = "#3d4856"
    primaryColor = "#ff9e00"
    lightColor = "#d6d6d6"
    lightestColor = "#fff"
